---
title: "S&P 500 & Covid-19"
author: "Handerson Coq"
date: '2022-07-04'
output: html_document
---

Cleaning S&P500 data from Yahoo and covid-19 data from Johns Hopkins.


```{r packages}

#install.packages("quantmod")
library(quantmod)

library(dplyr)
library(tidyr)

```


### Get stock data

```{r}

getSymbols("^GSPC", src = "yahoo", from = Sys.Date()-(4*365), to = Sys.Date())


```

### Calcluate daily returns

```{r adding returns}

GSPC$GSPC.Return = diff(GSPC$GSPC.Adjusted)/Lag(GSPC$GSPC.Adjusted)

```


```{r get data}

### Add the data in a dataframe with dates for export

S_P500 <- data.frame(date = time(GSPC), open = GSPC$GSPC.Open, high = GSPC$GSPC.High, low = GSPC$GSPC.Low, close = GSPC$GSPC.Close, volume = GSPC$GSPC.Volume, adjusted = GSPC$GSPC.Adjusted, return = GSPC$GSPC.Return)

```

### Get covid data

```{r}

casesRaw <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")

deathsRaw <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")

recoveredRaw <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")

```

### Data cleaning

```{r cleaning}

### from wide to long

cases <- casesRaw %>%
  gather(key="date", value="confirmed", -c(Country.Region, Province.State, Lat, Long)) %>% 
  group_by(Country.Region, date) %>%
  summarize(cases=sum(confirmed))

deaths <- deathsRaw %>% 
  gather(key="date", value="deaths", -c(Country.Region, Province.State, Lat, Long)) %>% 
  group_by(Country.Region, date) %>% 
  summarize(deaths=sum(deaths))

recovered <- recoveredRaw %>% 
  gather(key="date", value="recovered", -c(Country.Region, Province.State, Lat, Long)) %>% 
  group_by(Country.Region, date) %>% summarize(recovered=sum(recovered))

### Combining the data

covidData <- full_join(cases, deaths) %>% 
  full_join(recovered)

### formatting date

covidData$date <- covidData$date %>% 
  sub("X", "", .) %>% 
  as.Date("%m.%d.%y")

### Aggregating cases

covidData <- covidData %>% 
  group_by(Country.Region) %>% 
  mutate(cumCases=cumsum(cases), days = date - first(date) + 1)

### Data for the world

worldCovid <- covidData %>%
  group_by(date) %>%
  summarize(cases=sum(cases), cumCases=sum(cumCases), deaths=sum(deaths), recovered=sum(recovered))

### Data for the U.S.

usCovid <- covidData %>%
  filter(Country.Region=="US") %>%
  select(date, cases, deaths, recovered) %>% 
  arrange(date) %>% 
  rename(usCases = cases, usDeaths = deaths, usRecovered = recovered)

### Add the change in case

usCovid$change <- diff(usCovid$usCases)/Lag(usCovid$usCases)

```

### Putting covid-19 data and stock data together

```{r}

SP500_covid <- full_join(filter(S_P500, date >= '2020-01-01'), usCovid[,-1]) %>% 
  full_join(worldCovid)

```


### Exporting data

```{r}

write.csv(S_P500, file="S_P500.csv", quote=F)

write.csv(covidData, file="covid_19.csv", quote=F)

write.csv(SP500_covid, file="SP500_covid19.csv", quote=F)

```



